### ISSUE TITLE
Spam log when load failed url media network

### ISSUE THREAD

**Issue by trunghieuvn** [alexmercerind/dart_vlc#144]
i use version `dart_vlc: ^0.1.7` 

Given: load url media network failed
When: call player.play()
Then: spam log "Unhandled Exception: Null check operator used on a null value"

please not use `!` please check null or something solution for this case.
thank so much 

<img width="1556" alt="Screen Shot 2021-08-31 at 12 38 59 AM" src="https://user-images.githubusercontent.com/19247680/131381241-1ba2d0b3-368b-4b17-add8-d0906e167d15.png">

## Logs:

```
ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      receiver.<anonymous closure>
package:dart_vlc_ffi/…/internal/ffi.dart:200
#1      _rootRunUnary (dart:async/zone.dart:1370:13)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#7      _StreamController._add (dart:async/stream_controller.dart:607:7)
#8      _StreamController.add (dart:async/stream_controller.dart:554:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      receiver.<anonymous closure>
package:dart_vlc_ffi/…/internal/ffi.dart:200
#1      _rootRunUnary (dart:async/zone.dart:1370:13)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#7      _StreamController._add (dart:async/stream_controller.dart:607:7)
#8      _StreamController.add (dart:async/stream_controller.dart:554:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value

```

## widget render:
<img width="709" alt="Screen Shot 2021-08-31 at 12 37 03 AM" src="https://user-images.githubusercontent.com/19247680/131381193-16a4b2fa-4030-435e-ba67-85f4782efd56.png">

**Comment by alexmercerind** [comment]
Did you hot restart?
