### ISSUE TITLE
CMake 3.15 or higher is required.  You are running version 3.10.2

### ISSUE THREAD

**Issue by xiaocode** [alexmercerind/dart_vlc#16]
I cloned this project, and run 'flutter run' in the 'example' folder.then I got this issue:

```
~/github/dart_vlc/example$ flutter run
Launching lib/main.dart on Linux in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/CMakeLists.txt:9 (cmake_minimum_required):
  CMake 3.15 or higher is required.  You are running version 3.10.2  
```

**Comment by DomingoMG** [comment]
Yesterday I had a similar problem on another computer.

When installing Visual Studio Community 2019 you must install the C ++ add-ons, compilations and creating apps in c ++
[Visual Studio Community 2019, click here](https://visualstudio.microsoft.com/es/downloads/)

**Comment by alexmercerind** [comment]
@xiaocode , its not a problem with your plugin but the CMake on your linux is older.

Please install the updated version using apt.

**Comment by DomingoMG** [comment]
@xiaocode @alexmercerind 
Yesterday I had this similar error on Windows.
If it works for you, my solution was to do this.

Uninstall Visual Studio Community 2019 and reinstall it
Selecting the two yellow options

![1](https://user-images.githubusercontent.com/36201422/115582926-526a0600-a2c1-11eb-8be7-36ef414c3009.PNG)

**Comment by alexmercerind** [comment]
@xiaocode, please let me know when your issue is resolved. its important to keep track for us.

**Comment by xiaocode** [comment]
@DomingoMG @alexmercerind I have already update the cmake in my ubuntu.But nothing changed! I noticed that the CMakeCache.txt has the line: 'CMAKE_ROOT:INTERNAL=/snap/flutter/81/usr/share/cmake-3.10'.

**Comment by alexmercerind** [comment]
@xiaocode , as you have cloned this repo, you may try to downgrade the CMake version in this file.

https://github.com/alexmercerind/dart_vlc/blob/b039c575050386c6d51acbea2cac1239cab956e7/windows/CMakeLists.txt#L9

And, make a pull request if it works even after downgrading the version, as we don't really care about version. (all that we need is functioning)

**Comment by xiaocode** [comment]
@alexmercerind unfortunately!It doesn`t work...
```
[   +2 ms] cd /home/yxy/github/dart_vlc/example/build/linux/debug/flutter && /snap/flutter/81/usr/bin/cmake -E env FLUTTER_ROOT=/home/yxy/snap/flutter/common/flutter
PROJECT_DIR=/home/yxy/github/dart_vlc/example DART_OBFUSCATION=false TRACK_WIDGET_CREATION=true TREE_SHAKE_ICONS=false
PACKAGE_CONFIG=/home/yxy/github/dart_vlc/example/.dart_tool/package_config.json FLUTTER_TARGET=/home/yxy/github/dart_vlc/example/lib/main.dart
/home/yxy/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.sh Debug
[        ] Unhandled exception:
[        ] RangeError (index): Invalid value: Only valid value is 0: 1
[        ] #0      List.[] (dart:core-patch/array.dart:110:52)
[        ] #1      main (file:///home/yxy/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.dart:14:37)
[        ] #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
[        ] #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[        ] ninja: build stopped: subcommand failed.
[  +14 ms] Building Linux application... (completed in 382ms)
[+6293 ms] Exception: Build process failed
[   +3 ms] "flutter run" took 7,132ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
```

**Comment by tomassasovsky** [comment]
I had this problem and solved it by uninstalling flutter from the snap package manager and installing it from the Github repository. You can simply follow [this guide](https://flutter.dev/docs/get-started/install/linux).

I hope this helps!

**Comment by alexmercerind** [comment]
Closing this issue, as @tomassasovsky's solution for CMake works out.

**Comment by xiaocode** [comment]
@tomassasovsky Thank you!It works!But I got another issue:

```
[ +489 ms] [3/9] Building CXX object CMakeFiles/dart_vlc_example.dir/main.cc.o
[   +2 ms] [4/9] Building CXX object CMakeFiles/dart_vlc_example.dir/flutter/generated_plugin_registrant.cc.o
[  +80 ms] [5/9] Building CXX object CMakeFiles/dart_vlc_example.dir/my_application.cc.o
[+1117 ms] [6/9] Building CXX object plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o
[        ] FAILED: plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o 
[   +7 ms] /usr/bin/clang++ -DAPPLICATION_ID=\"com.example.dart_vlc\" -DFLUTTER_PLUGIN_IMPL -Ddart_vlc_plugin_EXPORTS
-I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin
-I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/INTERFACE
-I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/include -I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral -isystem /usr/include/gtk-3.0
-isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/gio-unix-2.0
-isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/fribidi -isystem /usr/include/harfbuzz -isystem /usr/include/atk-1.0 -isystem /usr/include/pixman-1 -isystem
/usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem
/usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -g -fPIC -fvisibility=hidden -Wall -Werror -pthread -std=gnu++17 -MD -MT
plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o -MF plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o.d -o
plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o -c /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc
[   +4 ms] /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc:98:17: error: redefinition of 'player'
[   +2 ms]         Player* player = players->get(id);
[        ]                 ^
[        ] /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc:95:17: note: previous definition is here
[        ]         Player* player = players->get(id);
[        ]                 ^
[        ] /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc:187:25: error: cannot initialize a variable of type 'const char *' with
an rvalue of type 'FlValue *' (aka '_FlValue *')
[        ]             const char* playlistMode = fl_value_lookup_string(source, "playlistMode");
[        ]                         ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[        ] 2 errors generated.
[        ] ninja: build stopped: subcommand failed.
[  +14 ms] Building Linux application... (completed in 18.4s)
[        ] Exception: Build process failed
[   +1 ms] "flutter run" took 18,895ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:664:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1059:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
```

**Comment by tomassasovsky** [comment]
@xiaocode a few questions:
Did you ```flutter clean``` and ```flutter pub get```?

Two apt packages are required (not snap), do you have them installed? (you can install them both with this command: ```sudo apt-get install libvlc-dev && sudo apt-get install vlc```)

**Comment by xiaocode** [comment]
@tomassasovsky Yes!I did it!But problem still existed...
