### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by xiaocode** [alexmercerind/dart_vlc#17]
After I solved the flutter installed by snap,I got a new problem when run command 'flutter run'.

```
[ +489 ms] [3/9] Building CXX object CMakeFiles/dart_vlc_example.dir/main.cc.o
[   +2 ms] [4/9] Building CXX object CMakeFiles/dart_vlc_example.dir/flutter/generated_plugin_registrant.cc.o
[  +80 ms] [5/9] Building CXX object CMakeFiles/dart_vlc_example.dir/my_application.cc.o
[+1117 ms] [6/9] Building CXX object plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o
[        ] FAILED: plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o 
[   +7 ms] /usr/bin/clang++ -DAPPLICATION_ID=\"com.example.dart_vlc\" -DFLUTTER_PLUGIN_IMPL -Ddart_vlc_plugin_EXPORTS
-I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin
-I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/INTERFACE
-I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/include -I/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral -isystem /usr/include/gtk-3.0
-isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/gio-unix-2.0
-isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/fribidi -isystem /usr/include/harfbuzz -isystem /usr/include/atk-1.0 -isystem /usr/include/pixman-1 -isystem
/usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem
/usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -g -fPIC -fvisibility=hidden -Wall -Werror -pthread -std=gnu++17 -MD -MT
plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o -MF plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o.d -o
plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o -c /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc
[   +4 ms] /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc:98:17: error: redefinition of 'player'
[   +2 ms]         Player* player = players->get(id);
[        ]                 ^
[        ] /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc:95:17: note: previous definition is here
[        ]         Player* player = players->get(id);
[        ]                 ^
[        ] /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin.cc:187:25: error: cannot initialize a variable of type 'const char *' with
an rvalue of type 'FlValue *' (aka '_FlValue *')
[        ]             const char* playlistMode = fl_value_lookup_string(source, "playlistMode");
[        ]                         ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[        ] 2 errors generated.
[        ] ninja: build stopped: subcommand failed.
[  +14 ms] Building Linux application... (completed in 18.4s)
[        ] Exception: Build process failed
[   +1 ms] "flutter run" took 18,895ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:664:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1059:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
```

**Comment by DomingoMG** [comment]
@alexmercerind, @xiaocode 
This error is due to my implementation of **playlistMode**.
It was not tested on Linux since I don't have Linux.

When you create an instance of **Playlist (media: [], playlistMode: PlaylistMode.single);**

**Comment by alexmercerind** [comment]
@xiaocode , now you can clone and use it on linux. sorry for all the mishaps & mistakes.
