### ISSUE TITLE
Exception: Build process failed

### ISSUE THREAD

**Issue by xiaocode** [alexmercerind/dart_vlc#20]
I pull the latest version, new problem happen!My OS is Ubuntu 20.04.

```
[  +53 ms] executing: uname -m
[  +34 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +12 ms] executing: [/home/yxy/Software/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5865c14d67dc300a1206f45dd50d869844e24349
[   +1 ms] executing: [/home/yxy/Software/flutter/] git tag --points-at 5865c14d67dc300a1206f45dd50d869844e24349
[  +13 ms] Exit code 0 from: git tag --points-at 5865c14d67dc300a1206f45dd50d869844e24349
[   +1 ms] executing: [/home/yxy/Software/flutter/] git describe --match *.*.* --long --tags 5865c14d67dc300a1206f45dd50d869844e24349
[  +33 ms] Exit code 0 from: git describe --match *.*.* --long --tags 5865c14d67dc300a1206f45dd50d869844e24349
[        ] 2.2.0-10.0.pre-215-g5865c14d67
[  +12 ms] executing: [/home/yxy/Software/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/yxy/Software/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://hub.fastgit.org/flutter/flutter.git
[  +82 ms] executing: [/home/yxy/Software/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +54 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] executing: /home/yxy/Android/Sdk/platform-tools/adb devices -l
[  +48 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +58 ms] Skipping pub get: version match.
[  +30 ms] Found plugin path_provider at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +4 ms] Found plugin path_provider_linux at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_macos at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +2 ms] Found plugin path_provider_windows at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +14 ms] Found plugin dart_vlc at /home/yxy/github/dart_vlc/
[  +34 ms] Found plugin path_provider at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +2 ms] Found plugin path_provider_linux at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_macos at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +3 ms] Found plugin path_provider_windows at /home/yxy/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +19 ms] Found plugin dart_vlc at /home/yxy/github/dart_vlc/
[  +97 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +4 ms] Launching lib/main.dart on Linux in debug mode...
[   +5 ms] /home/yxy/Software/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/yxy/Software/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/yxy/Software/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.WSJXGF/flutter_tool.QGMDON/app.dill --packages /home/yxy/github/dart_vlc/example/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +26 ms] Building Linux application...
[   +9 ms] <- compile package:dart_vlc_example/main.dart
[   +5 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/yxy/github/dart_vlc/example/linux
[+120696 ms] -- Configuring done
[  +12 ms] -- Generating done
[  +10 ms] -- Build files have been written to: /home/yxy/github/dart_vlc/example/build/linux/x64/debug
[   +6 ms] executing: ninja -C build/linux/x64/debug install
[  +12 ms] ninja: Entering directory `build/linux/x64/debug'
[  +11 ms] [1/9] Running utility command for LIBVLC_EXTRACT
[        ] FAILED: plugins/dart_vlc/CMakeFiles/LIBVLC_EXTRACT.util 
[  +20 ms] cd /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin && /snap/cmake/858/bin/cmake -E tar xzf
"/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin/libvlcpp.zip" && /snap/cmake/858/bin/cmake -E copy_directory
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin/libvlcpp-master/vlcpp
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/include/vlcpp
[   +4 ms] Error copying directory from "/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin/libvlcpp-master/vlcpp" to
"/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/include/vlcpp".
[+2588 ms] [2/9] Generating /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/yxy/github/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +2 ms] [  +51 ms] executing: uname -m
[        ] [  +27 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +9 ms] executing: [/home/yxy/Software/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 5865c14d67dc300a1206f45dd50d869844e24349
[        ] [        ] executing: [/home/yxy/Software/flutter/] git tag --points-at 5865c14d67dc300a1206f45dd50d869844e24349
[        ] [  +17 ms] Exit code 0 from: git tag --points-at 5865c14d67dc300a1206f45dd50d869844e24349
[        ] [   +3 ms] executing: [/home/yxy/Software/flutter/] git describe --match *.*.* --long --tags 5865c14d67dc300a1206f45dd50d869844e24349
[        ] [  +32 ms] Exit code 0 from: git describe --match *.*.* --long --tags 5865c14d67dc300a1206f45dd50d869844e24349
[        ] [        ] 2.2.0-10.0.pre-215-g5865c14d67
[        ] [  +12 ms] executing: [/home/yxy/Software/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/yxy/Software/flutter/] git ls-remote --get-url origin
[        ] [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://hub.fastgit.org/flutter/flutter.git
[        ] [  +53 ms] executing: [/home/yxy/Software/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +45 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +67 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +25 ms] Initializing file store
[        ] [   +4 ms] Done initializing file store
[        ] [  +27 ms] Skipping target: gen_localizations
[        ] [ +991 ms] Skipping target: unpack_linux
[        ] [ +266 ms] Skipping target: kernel_snapshot
[        ] [ +191 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [   +7 ms] "flutter assemble" took 1,611ms.
[        ] [ +256 ms] ensureAnalyticsSent: 253ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[        ] ninja: build stopped: subcommand failed.
[  +13 ms] Building Linux application... (completed in 123.4s)
[   +1 ms] Exception: Build process failed
[   +4 ms] "flutter run" took 124,359ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:664:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1059:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by alexmercerind** [comment]
I believe you're from China, make sure that GitHub is accessible from your computer.

**Comment by xiaocode** [comment]
@alexmercerind Yes!I`m from China.I notice that issue,and I delete the folder 'linux/bin', but it doesn`t work.So how can I solve this problem?

**Comment by k1ycee** [comment]
I'm having the same issue too @xiaocode did you get any solution yet?

**Comment by alexmercerind** [comment]
@xiaocode & @k1ycee ,
I'm really sorry to hear the problem.

For now, you can download [libvlcpp master ZIP](https://github.com/videolan/libvlcpp/archive/refs/heads/master.zip) and paste it as follows with name `libvlcpp.zip`. After that, your project will compile successfully.

It is happening because CMake can't access GitHub on your development machine.

![Screenshot from 2021-04-23 11-30-55](https://user-images.githubusercontent.com/28951144/115825665-62035f00-a427-11eb-9fd4-e49a50fcc63d.png)

**Comment by xiaocode** [comment]
@alexmercerind Thanks a lot!I finally got it work!My solution is replace the url 'github.com' with 'hub.fastgit.org' in CMakeList.txt file.
It's a proxy url for github.com.

**Comment by k1ycee** [comment]
Oh wow I had to just use git directly for mine to start working. 
@alexmercerind this is really awesome work you've done thank you for being awesome
