### ISSUE TITLE
IOS Unhandled Exception: MissingPluginException(No implementation found for method PlayerRegisterTexture on channel dart_vlc)

### ISSUE THREAD

**Issue by kiam123** [alexmercerind/dart_vlc#219]
IOS APP will this error, how to fix them?

`error`
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method PlayerRegisterTexture on channel dart_vlc)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      new Player.<anonymous closure> (package:dart_vlc/dart_vlc.dart:61:25)
<asynchronous suspension>
```

`flutter and dart version`
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 個月前) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by kiam123** [comment]
this is my sample code

```
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:dart_vlc/dart_vlc.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path_provider/path_provider.dart';

void main() {
  DartVLC.initialize();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Player player = Player(id: 0);

  @override
  void initState() {
    super.initState();
    
    load();
  }

  @override
  void dispose() {
    super.dispose();
  }

  Future<File> getFileFromAsset(String path) async {
    final byteData = await rootBundle.load('$path');  

    final file = File('${(await getTemporaryDirectory()).path}/tmp');
    await file.writeAsBytes(byteData.buffer.asUint8List(byteData.offsetInBytes, byteData.lengthInBytes));

    return file;
  }

  load() async{
    this.player.open(Media.file(await getFileFromAsset("assets/rtp.sdp")));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: InkWell(
              child: Container(
                width: 1100,
                height: 650,
                
                child: Video(
                    player: player,
                    width: 320,
                    height: 240,
                    volumeThumbColor: Colors.blue,
                    volumeActiveColor: Colors.blue,
                  ),
              ),
              onTap: () { 
                  player.play();
              },
            ),
      ),
    );
  }
}

```
