### ISSUE TITLE
`NativeVideo`: flickering under certain arrangements 

### ISSUE THREAD

**Issue by zezo357** [alexmercerind/dart_vlc#256]
**Describe the bug**
Using the native video widget some times application crash(without showing any errors)
and if it works the audio is playing correctly but with no output (black screen ) also a small window pops up in the center of the black screen and then disappers (doesent have text inside it from what i saw)

**Media** 

both url and local files does the same bug

**Minimal reproducible code**

```dart
followed example code
```

**Flutter logs**
output is too long so i cant provide it
```
```

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19043.1586], locale en-US)
    • Flutter version 2.10.4 at G:\My Work HDD2\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\zezo_\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.65.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.29

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Operating system:**
- Platform: Windows.
- OS version: Windows 10 21H1.

- [x] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise, do nothing.

**Imported using**
```
dependencies:
  dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master

dependency_overrides:
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master
      path: ffi
```

**Comment by alexmercerind** [comment]
Is the same behaviour present in the example app of the repo?
I know currently that hot-restart doesn't work & some crash happens at times.

**Comment by alexmercerind** [comment]
I'd need some feedback on this one to proceed.

**Comment by zezo357** [comment]
will clone the example app to be sure 100%

**Comment by zezo357** [comment]
trying to run the example code cloned 
gave me this error
```
CMake Error at flutter/generated_plugins.cmake:12 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/dart_vlc/windows" which is not an
  existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)
```


so i created a new project with the example code and did the setup steps 
adding the lines in main.cpp and importing the package from github 

this showed up when building (maybe it will help )
```
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(471,59): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(492,51): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(503,57): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(504,46): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(504,59): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(510,72): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(511,46): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(511,59): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
G:\My Work HDD2\AndroidStudioProjects\example_test\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\player\player.cc(313,9): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [G:\My Work HDD2\AndroidStudioProjects\example_test\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
```



ok example is working as expected

will try to follow what is the step i missed.

**Comment by zezo357** [comment]
in case of my app 

in same run 
first video (audio no video)
second video (crash)(even if i made a hot restart )

i have to restart the app to be able to test again 



for the video ouput rebuilding the NativeVideo widget i think is the problem (i am not sure and will try to test to be sure)

when i try to hotrestart with the video player on screen this error happens
```
Hot Restart Error hot restart failed to complete: kill: (112) Service has disappeared #0 new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45) #1 VmService._call (package:vm_service/src/vm_service.dart:2225:21) #2 VmService.kill (package:vm_service/src/vm_service.dart:2060:7) #3 HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:633:49)   #4 HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:760:16)   #5 HotRunner.restart (package:flutter_tools/src/run_hot.dart:707:38)  
```

**Comment by alexmercerind** [comment]
I'm aware of the hot-restart problem. I will release few patches to `NativeView` in upcoming days.
https://github.com/alexmercerind/dart_vlc/blob/dc71ce3a2d7a9203d6f8d11a25dad1fa8a05351e/lib/src/hwnd.dart#L9-L15

Make sure to follow these steps in your codebase too:
https://github.com/alexmercerind/flutter_native_view#setup
https://github.com/alexmercerind/dart_vlc#nativevideo

Thanks.

**Comment by zezo357** [comment]
Just in case my code is the problem 

Also i had the same code using the normal video widget and it was working as expected
main.cpp
```
#include <flutter/dart_project.h>
#include <flutter/flutter_view_controller.h>
#include <windows.h>
#include "flutter_native_view/flutter_native_view_plugin.h"
#include "flutter_window.h"
#include "utils.h"

int APIENTRY wWinMain(_In_ HINSTANCE instance, _In_opt_ HINSTANCE prev,
                      _In_ wchar_t *command_line, _In_ int show_command) {
  // Attach to console when present (e.g., 'flutter run') or create a
  // new console when running with a debugger.
  if (!::AttachConsole(ATTACH_PARENT_PROCESS) && ::IsDebuggerPresent()) {
    CreateAndAttachConsole();
  }

  // Initialize COM, so that it is available for use in the library and/or
  // plugins.
  ::CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);

  flutter::DartProject project(L"data");

  std::vector<std::string> command_line_arguments =
      GetCommandLineArguments();

  project.set_dart_entrypoint_arguments(std::move(command_line_arguments));

  FlutterWindow window(project);
  Win32Window::Point origin(10, 10);
  Win32Window::Size size(1280, 720);
  if (!window.CreateAndShow(L"anime_here", origin, size)) {
    return EXIT_FAILURE;
  }
  window.SetQuitOnClose(true);
  flutternativeview::CreateNativeViewContainer();
  ::MSG msg;
  while (::GetMessage(&msg, nullptr, 0, 0)) {
    ::TranslateMessage(&msg);
    ::DispatchMessage(&msg);
  }

  ::CoUninitialize();
  return EXIT_SUCCESS;
}

```

main.dart
``` dart
void main() async {
  if (Platform.isWindows) {
    await DartVLC.initialize(useFlutterNativeView: true);
  }

  /// STEP 1. Create catcher configuration.
  /// Debug configuration with dialog report mode and console handler. It will show dialog and once user accepts it, error will be shown   /// in console.
  CatcherOptions debugOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), []);

  /// Release configuration. Same as above, but once user accepts dialog, user will be prompted to send email with crash to support.
  CatcherOptions releaseOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), []);

  /// STEP 2. Pass your root widget (MyApp) along with Catcher configuration:
  catcher = Catcher(
      rootWidget: MyApp(),
      ensureInitialized: true,
      debugConfig: debugOptions,
      releaseConfig: releaseOptions);

}
```

how i create the controller
```
Player _createVideoControllerWindows(DataSource dataSource, Duration seekTo) {
    Random random = Random();
    int randomNumber = random.nextInt(1000);
    String refer;
    if (dataSource.type == DataSourceType.network) {
      refer = dataSource.httpHeaders!["Referer"] ?? "";
    } else {
      refer = "";
    }
    //print('--http-referrer=' + refer);
    Player player = Player(
        id: randomNumber,
        commandlineArguments: [
          //"-vvv",
          '--http-referrer=' + refer,
          '--http-reconnect',
        ],
        registerTexture: false); // create a new video controller
    player = setPlayerDataSource(dataSource, player, seekTo);
    return player;
  }

  setPlayerDataSource(DataSource dataSource, Player player, seekTo) {
    duration.value = Duration.zero;
    if (dataSource.type == DataSourceType.asset) {
      player.open(
        Media.asset(dataSource.source!),
        autoStart: _autoplay,
      );
    } else if (dataSource.type == DataSourceType.network) {
      print(dataSource.source!);
      player.open(
        Media.network(
          dataSource.source!,
          timeout: Duration(seconds: 10),
          //startTime: seekTo
        ),
        autoStart: _autoplay,
      );
    } else {
      player.open(
        Media.file(
          dataSource.file!,
          //startTime: seekTo
        ),
        autoStart: _autoplay,
      );
    }
    if (seekTo != Duration.zero) {
      this.seekTo(seekTo);
    }
    return player;
  }
```



Native video in my ui
```
LayoutBuilder(
      builder: (ctx, constraints) {
        final responsive = Responsive(
          constraints.maxWidth,
          constraints.maxHeight,
        );

        if (widget.customIcons != null) {
          _.customIcons = this.widget.customIcons!(responsive);
        }

        if (widget.header != null) {
          _.header = this.widget.header!(context, _, responsive);
        }

        if (widget.bottomRight != null) {
          _.bottomRight = this.widget.bottomRight!(context, _, responsive);
        }

        return Stack(
          alignment: Alignment.center,
          children: [
            if (_.windows)
              RxBuilder(
                  //observables: [_.videoFit],
                  (__) {
                print("NATIVE HAS BEEN REBUILT");
                _.dataStatus.status.value;
                return Stack(
                  fit: StackFit.expand,
                  children: [
                    NativeVideo(
                      player: _.videoPlayerControllerWindows!,
                      width: 640,
                      showControls: false,
                      height: 480,
                      //playlistLength: 1,
                    ),
                  ],
                );
              })
            else
              RxBuilder(
                  //observables: [_.videoFit],
                  (__) {
                _.dataStatus.status.value;
                print("Fit is ${widget.controller.videoFit.value}");
                return SizedBox.expand(
                  child: FittedBox(
                    fit: widget.controller.videoFit.value,
                    child: SizedBox(
                      width: _.videoPlayerController != null
                          ? _.videoPlayerController!.value.size.width
                          : 640,
                      height: _.videoPlayerController != null
                          ? _.videoPlayerController!.value.size.height
                          : 480,
                      child: VideoPlayer(_.videoPlayerController!),
                    ),
                  ),
                );
              }),
            ClosedCaptionView(responsive: responsive),
            if (_.controlsEnabled && _.controlsStyle == ControlsStyle.primary)
              PrimaryVideoPlayerControls(
                responsive: responsive,
              ),
            if (_.controlsEnabled && _.controlsStyle == ControlsStyle.secondary)
              SecondaryVideoPlayerControls(
                responsive: responsive,
              ),
          ],
        );
      },
    );
```

**Comment by alexmercerind** [comment]
@zezo357 thanks for jotting the information. I'll have look at things. Do you mind sharing your code in a repo (private if you wish, add me as a collaborator)?
Again, I'm bit occupied with things again, but I'll try to fix the stuff up here in plugin.

**Comment by zezo357** [comment]
@alexmercerind 
i will make the video player package seprated from my code as a repo 
then add you so its easier for you

**Comment by zezo357** [comment]
@alexmercerind 
I created the repo and added you as collaborator

you will find the master branch is using normal video widget
while testing native is the one with native widget

**Comment by zezo357** [comment]
after applying everything now the video output works

**Comment by zezo357** [comment]
Didnt find the main problem cause 

but thanks ♥

but playing two videos still crashes the app (two player controllers get created)

also when i opened the video and put the task manger window over it the video was switching to black and back
example to what is happening 

https://user-images.githubusercontent.com/25157308/162651215-c26be8dd-ca09-4652-adb7-81bc48c57bae.mp4

**Comment by alexmercerind** [comment]
There should be no crashes now & hot-reload will work fine. The flickering issue can't be reproduced in the example app, possibly some Dart side painting issue.

**Comment by zezo357** [comment]
> There should be no crashes now & hot-reload will work fine. The flickering issue can't be reproduced in the example app, possibly some Dart side painting issue.
> 
> Feel free to drop feedback here or re-open issue in case some other problem is noticed.

The flickering issue is still happening to me,

if possible, can you check the repository to check what may be the problem?
I added you as a collaborator

you will find the master branch is using the normal video widget
while testing native is the one with native widget

**Comment by aenckli** [comment]
I found the flickering issue too. For testing purpose, I used the repo example, and added a button to navigate from main page to a video player page. The page code is below. Flickering happens when mouse hovers over control buttons and without Listview wrapped over NativeVideo. With the Listview, seems normal.

```
class VideoPlayerPage extends StatefulWidget {
  final String video;

  const VideoPlayerPage({
    Key? key,
    required this.video,
  }) : super(key: key);

  @override
  _VideoPlayerPageState createState() => _VideoPlayerPageState();
}

class _VideoPlayerPageState extends State<VideoPlayerPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Video Player')),
      body: VideoPlayerDesktop(
        video: widget.video,
      )
    );
  }
}

class VideoPlayerDesktop extends StatefulWidget {
  final String video;

  const VideoPlayerDesktop({
    Key? key,
    required this.video,
  }) : super(key: key);

  @override
  State<VideoPlayerDesktop> createState() => _VideoPlayerDesktopState();
}

class _VideoPlayerDesktopState extends State<VideoPlayerDesktop> {
  Player player = Player(
    id: 100,
    // videoDimensions: VideoDimensions(640, 360),
    registerTexture: !Platform.isWindows,
  );
  VideoDimensions videoSize = VideoDimensions(0, 0);

  @override
  void initState() {
    super.initState();
    player.open(Media.file(File(p.join(widget.video))), autoStart: false);
    player.playback.isSeekable = true;
  }

  @override
  Widget build(BuildContext context) {
    return NativeVideo(
      player: player,
      width: 640,
      height: 360,
      showControls: true,
    );

    return ListView(
      padding: const EdgeInsets.all(4.0),
      children: [
        NativeVideo(
            player: player,
            width: 640,
            height: 360,
            showControls: true,
          )
    ]
    );
  }
}

```

To maximize the size of NativeVideo in window, I used Container instead of Listview, but flickering still exists.

```
    return Container(
      child: NativeVideo(
        player: player,
        // width: 640,
        // height: 360,
        showControls: true,
      ),
    );

```

**Comment by zezo357** [comment]
@alexmercerind  I cant find a way to reopen the issue but aenckli found out the problem cause i guess

**Comment by alexmercerind** [comment]
The flickering is caused by `CustomPainter` & I'm not sure how to address it. In some situations, like the example app, it works fine but other times it doesn't.

https://github.com/alexmercerind/flutter_native_view/blob/1659d67cdfe300b43f0619518bea9f62f5a70ef7/lib/src/widgets.dart#L155-L183

**Comment by alexmercerind** [comment]
> testing on flutter 3 and the issue is gone
> 
> I wonder if they fixed the problem with CustomPainter

Great. Should this be closed then?

**Comment by aenckli** [comment]
Briefly tested using flutter 3, the problem is gone.

**Comment by zezo357** [comment]
> > testing on flutter 3 and the issue is gone
> > I wonder if they fixed the problem with CustomPainter
> 
> Great. Should this be closed then?

yes i found another problems so i will new issue for those

**Comment by alexmercerind** [comment]
> yes i found another problems so i will new issue for those

feel free to skip the details in issue template.
