### ISSUE TITLE
Media Parse dynamicLibary not initialized

### ISSUE THREAD

**Issue by Selemba1000** [alexmercerind/dart_vlc#352]
**Describe the bug**
When trying to parse a Media File via `Media.file(parse: true)` the error is posted to the log, and execution stops.

**Media**

Media independent...

**Minimal reproducible code**
```dart
void main(){
  Media media = Media.file(File(*path*),parse: true, timeout: Duration(seconds: 10));
}
```

**Flutter logs**
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
Debug service listening on ws://127.0.0.1:35323/VSMub4Dt86U=/ws
Syncing files to device Linux...
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'dynamicLibrary' has not been initialized.
#0      dynamicLibrary (package:dart_vlc_ffi/src/internal/dynamiclibrary.dart)
#1      MediaFFI.parse (package:dart_vlc_ffi/src/internal/ffi.dart:121:39)
#2      MediaFFI.parse (package:dart_vlc_ffi/src/internal/ffi.dart)
#3      Media.parse (package:dart_vlc_ffi/src/media_source/media.dart:172:45)
#4      new MusikStore (package:danza/MusikBib/storage.dart:20:14)
#5      main (package:+++++/main.dart:8:3)
#6      _runMain.<anonymous closure> (dart:ui/hooks.dart:134:23)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

```
```
[✓] Flutter (Channel stable, 3.3.10, on openSUSE Tumbleweed 6.1.0-1-default,
    locale de_DE.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/selemba/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (vor 3 Wochen), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/selemba/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at:
      /home/selemba/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7
      172.25.2113.9123335/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /var/lib/flatpak/exports/bin/com.google.Chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at
      /home/selemba/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7
      172.25.2113.9123335
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at
      /home/selemba/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52
    • Flutter plugin version 71.2.6
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • openSUSE Tumbleweed
      6.1.0-1-default
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124
      unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Operating system:**
- Platform: Linux
- OS version: openSUSE Tumbleweed 20230101

**Other details:**

- [x ] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [  ] I have donated / sponsored `dart_vlc`.

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise, do nothing.

**Comment by alexmercerind** [comment]
Add DartVLC.initialize first. Read the docs.

**Comment by Selemba1000** [comment]
thx
