### ISSUE TITLE
any instructions for getting running on mac ?

### ISSUE THREAD

**Issue by gedw99** [alexmercerind/dart_vlc#4]
Just gave it a try, but not sure what else to try.

pubspec:
````


flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
      mac:
        pluginClass: DartVlcPlugin

````

run:

````

flutter run -d mac --release
Launching lib/main.dart on macOS in release mode...
2021-03-24 12:06:53.316 xcodebuild[80655:3465381]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
Details:  (null) deviceType from bdf90dc799709a013a25d0fc2df80e441df026f3 was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7faec4b2fde0>                       
Method:   -platform                                                     
Thread:   <NSThread: 0x7faec4835500>{number = 3, name = (null)}         
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2021-03-24 12:06:53.708 xcodebuild[80655:3465502]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
Details:  (null) deviceType from bdf90dc799709a013a25d0fc2df80e441df026f3 was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7faec4b2fde0>                       
Method:   -platform                                                     
Thread:   <NSThread: 0x7faec4affbe0>{number = 8, name = (null)}         
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
Building macOS application...                                           

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method Player.create on channel dart_vlc)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
<asynchronous suspension>
#1      Player.create (package:dart_vlc/src/player.dart:63)
<asynchronous suspension>
#2      _DartVLCState.didChangeDependencies (package:dart_vlc_example/main.dart:31)
<asynchronous suspension>

**Comment by gedw99** [comment]
maybe the https://github.com/alexmercerind/dart_vlc/blob/master/ffi/main.dart needs to if def to load the framework ?

**Comment by alexmercerind** [comment]
Hi there @gedw99 !

Mac is not supported on this plugin. (atleast right now).

Thankyou.

**Comment by alexmercerind** [comment]
Since this issue was opened with a motive of a "question", a new similar issue is to track mac support (maybe) in future here #14.
