### ISSUE TITLE
slider.dart: Failed assertion: line 165 pos 15: 'value >= min && value <= max': is not true

### ISSUE THREAD

**Issue by Leadrive** [alexmercerind/dart_vlc#41]
````javascript
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building DartVLC(dirty, state: _DartVLCState#9fd40):
'package:flutter/src/material/slider.dart': Failed assertion: line 165 pos 15: 'value >= min &&
value <= max': is not true.

The relevant error-causing widget was:
  DartVLC file:///C:/tmp/dart_vlc/example/lib/main.dart:7:10

When the exception was thrown, this was the stack:
#2      new Slider (package:flutter/src/material/slider.dart:165:15)
#3      _DartVLCState.build (package:dart_vlc_example/main.dart:294:31)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4713:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4596:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4769:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4286:5)
#8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2583:33)
#9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:878:21)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:334:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1147:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1084:9)
#13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1000:5)
#17     _invoke (dart:ui/hooks.dart:163:10)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#19     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 5 frames from class _AssertionError and dart:async)
````

**Comment by alexmercerind** [comment]
Is this a one time issue?
Are you able to use plugin otherwise?

**Comment by Leadrive** [comment]
on the example, in the left area, I add a network file.
https://www.leadrive.cn/bee.mp4
after it play over, it will cause this error.
and it will loop playback, and the error will cause again.

**Comment by Leadrive** [comment]
````javascript
Flutter 2.3.0-1.0.pre.181 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3955ef0d02 (8 hours ago) • 2021-04-29 22:54:03 -0700
Engine • revision e7939e091e
Tools • Dart 2.14.0 (build 2.14.0-48.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.3.0-1.0.pre.181, on Microsoft Windows [Version 10.0.17763.1817], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio
[√] VS Code, 64-bit edition (version 1.55.2)
[√] Connected device (3 available)
````

**Comment by alexmercerind** [comment]
Thankyou for report.

**Comment by DomingoMG** [comment]
```
this.player?.open(
  new Playlist(
      medias: this.medias,
      playlistMode:
          PlaylistMode.loop),
);

```  
It is played again because in the demo there is a playlistMode.loop. I am going to further check the minimum and maximum error.

**Comment by DomingoMG** [comment]
Ok I know why it is, it is returning a value outside the range of the slider, I am going to do a pull request that solves the problem.

**Comment by Leadrive** [comment]
Hi, I updated the latest code. and the bug still exist.

````log
The following assertion was thrown building DartVLC(dirty, state: _DartVLCState#d92d4):
'package:flutter/src/material/slider.dart': Failed assertion: line 165 pos 15: 'value >= min &&
value <= max': is not true.

The relevant error-causing widget was:
  DartVLC file:///C:/tmp/dart_vlc/example/lib/main.dart:7:10

When the exception was thrown, this was the stack:
#2      new Slider (package:flutter/src/material/slider.dart:165:15)
#3      _DartVLCState.build (package:dart_vlc_example/main.dart:294:31)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4713:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4596:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4769:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4286:5)
#8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2583:33)
#9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:878:21)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:334:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1147:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1084:9)
#13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1000:5)
#17     _invoke (dart:ui/hooks.dart:163:10)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#19     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 5 frames from class _AssertionError and dart:async)
````

**Comment by Leadrive** [comment]
open, play, open, play..... maybe about 5 or 6 times.
the bug will caused.
Please check it.

**Comment by Leadrive** [comment]
@DomingoMG

**Comment by DomingoMG** [comment]
@Leadrive 
I will check it again.
But the error is due to the total length of the video, it seems to return null, I'll see what I can do.

**Comment by StarSkyGeminid** [comment]
Is this bug solved?
