### ISSUE TITLE
Can`t build example app on Linux

### ISSUE THREAD

**Issue by owl1n** [alexmercerind/dart_vlc#67]
Im using Flutter on linux and trying start example app on this OS.

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-17.0.pre.261, on Debian GNU/Linux 10 (buster) 4.19.0-10-amd64, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.

```

output from `flutter run -v -d linux`

```
[  +54 ms] executing: uname -m
[  +23 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/parallels/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[        ] executing: [/home/parallels/flutter/] git tag --points-at 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[  +14 ms] Exit code 0 from: git tag --points-at 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[   +1 ms] executing: [/home/parallels/flutter/] git describe --match *.*.* --long --tags 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[  +22 ms] Exit code 0 from: git describe --match *.*.* --long --tags 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[        ] 2.3.0-16.0.pre-261-g9ecba20fbd
[   +6 ms] executing: [/home/parallels/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/parallels/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +75 ms] Unable to locate an Android SDK.
[   +4 ms] executing: [/home/parallels/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +82 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +86 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] Skipping pub get: version match.
[  +26 ms] Found plugin path_provider at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +4 ms] Found plugin path_provider_linux at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +6 ms] Found plugin path_provider_macos at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +3 ms] Found plugin path_provider_windows at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +8 ms] Found plugin dart_vlc at /home/parallels/dart_vlc/
[  +33 ms] Found plugin path_provider at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +1 ms] Found plugin path_provider_linux at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_macos at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +1 ms] Found plugin path_provider_windows at /home/parallels/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +16 ms] Found plugin dart_vlc at /home/parallels/dart_vlc/
[ +110 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +3 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +1 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/parallels/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/parallels/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/parallels/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.HBSFLG/flutter_tool.OTGMGU/app.dill --packages
/home/parallels/dart_vlc/example/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill
--flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +26 ms] Building Linux application...
[  +31 ms] <- compile package:dart_vlc_example/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/parallels/dart_vlc/example/linux
[ +192 ms] -- Configuring done
[   +6 ms] -- Generating done
[   +3 ms] -- Build files have been written to: /home/parallels/dart_vlc/example/build/linux/x64/debug
[  +21 ms] executing: ninja -C build/linux/x64/debug install
[   +5 ms] ninja: Entering directory `build/linux/x64/debug'
[  +15 ms] [1/9] Running utility command for LIBVLC_EXTRACT
[        ] FAILED: plugins/dart_vlc/CMakeFiles/LIBVLC_EXTRACT.util 
[  +42 ms] cd /home/parallels/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin && /usr/local/bin/cmake -E tar xzf
"/home/parallels/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin/libvlcpp.zip" && /usr/local/bin/cmake -E
copy_directory /home/parallels/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin/libvlcpp-master/vlcpp
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/include/vlcpp
[   +3 ms] Error copying directory from
"/home/parallels/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/bin/libvlcpp-master/vlcpp" to
"/home/parallels/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/include/vlcpp".
[+3707 ms] [2/9] Generating /home/parallels/dart_vlc/example/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/parallels/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +2 ms] [ +125 ms] executing: uname -m
[        ] [  +32 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[   +7 ms] [   +6 ms] executing: [/home/parallels/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[        ] [        ] executing: [/home/parallels/flutter/] git tag --points-at 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[        ] [  +10 ms] Exit code 0 from: git tag --points-at 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[        ] [   +1 ms] executing: [/home/parallels/flutter/] git describe --match *.*.* --long --tags 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[        ] [  +24 ms] Exit code 0 from: git describe --match *.*.* --long --tags 9ecba20fbd351d1987ab9656c7bff51ba77daf2b
[        ] [        ] 2.3.0-16.0.pre-261-g9ecba20fbd
[        ] [   +4 ms] executing: [/home/parallels/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/master
[        ] [        ] executing: [/home/parallels/flutter/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +43 ms] Unable to locate an Android SDK.
[        ] [   +5 ms] executing: [/home/parallels/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [   +1 ms] master
[        ] [  +61 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +96 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [  +12 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +59 ms] Initializing file store
[        ] [  +13 ms] Done initializing file store
[        ] [  +42 ms] Skipping target: gen_localizations
[        ] [  +14 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +548 ms] Skipping target: unpack_linux
[        ] [ +511 ms] Skipping target: kernel_snapshot
[        ] [ +283 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +7 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +8 ms] "flutter assemble" took 1,635ms.
[        ] [ +120 ms] ensureAnalyticsSent: 117ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[        ] ninja: build stopped: subcommand failed.
[  +16 ms] Building Linux application... (completed in 4.1s)
[+5686 ms] Exception: Build process failed
[   +2 ms] "flutter run" took 10,244ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:671:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +32 ms] ensureAnalyticsSent: 30ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

Both libraries installed and available in Linux - `vlc` and `libvlc-dev` with stable versions 3.0.x

What happened?

**Comment by owl1n** [comment]
Fixed by deleting bin folder for Linux platform (seems like a zip file of vlcpp library was broken)
Maybe this a reference for #13 issue. I think libvlcpp need to be included to package without downloading this

**Comment by alexmercerind** [comment]
@owl1n glad you found it yourself. Sorry I didn't get time to reply back, apologies.
