### ISSUE TITLE
Fails to build snap

### ISSUE THREAD

**Issue by deut818** [alexmercerind/dart_vlc#71]
if i run ```snapcraft``` in my project folder, it fails with the following error;
```
Launching a VM.
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
The flutter plugin is currently in beta, its API may break. Use at your own risk.
snapd is not logged in, snap install commands will use sudo
snap "core18" has no updates available
Skipping pull flutter-extension (already ran)
Skipping pull gnome-3-28-extension (already ran)
Updating pull step for xifair-admin (source changed)
+ set -eux
+ rm -rf /root/project/build
+ snapcraftctl pull

ujSkipping build flutter-extension (already ran)
Building gnome-3-28-extension 
+ snapcraftctl build
make -j2 PLATFORM_PLUG=gnome-3-28-1804
make install PLATFORM_PLUG=gnome-3-28-1804 DESTDIR=/root/parts/gnome-3-28-extension/install
install -d /root/parts/gnome-3-28-extension/install/gnome-platform
install -d /root/parts/gnome-3-28-extension/install/data-dir
install -d /root/parts/gnome-3-28-extension/install/data-dir/icons
install -d /root/parts/gnome-3-28-extension/install/data-dir/sounds
install -d /root/parts/gnome-3-28-extension/install/data-dir/themes
install -D -m755 desktop-launch "/root/parts/gnome-3-28-extension/install/snap/command-chain"/desktop-launch
install -D -m755 hooks-configure-desktop "/root/parts/gnome-3-28-extension/install/snap/command-chain"/hooks-configure-desktop
Building xifair-admin 
+ snapcraftctl build
flutter pub get
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝


Running "flutter pub get" in build...                              47.5s
flutter build linux --release -v -t lib/main.dart
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[ +111 ms] executing: uname -m
[  +57 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +13 ms] executing: [/root/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 6b7f46353ffb0df0e72b4a91b0f86f85f9780533
[   +1 ms] executing: [/root/snap/flutter/common/flutter/] git tag --points-at 6b7f46353ffb0df0e72b4a91b0f86f85f9780533
[  +23 ms] Exit code 0 from: git tag --points-at 6b7f46353ffb0df0e72b4a91b0f86f85f9780533
[   +2 ms] executing: [/root/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags 6b7f46353ffb0df0e72b4a91b0f86f85f9780533
[  +52 ms] Exit code 0 from: git describe --match *.*.* --long --tags 6b7f46353ffb0df0e72b4a91b0f86f85f9780533
[        ] 2.3.0-16.0.pre-376-g6b7f46353f
[  +10 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/root/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +137 ms] Unable to locate an Android SDK.
[   +7 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +121 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +238 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +183 ms] Skipping pub get: version match.
[  +85 ms] Found plugin dart_vlc at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[  +15 ms] Found plugin disk_space at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/disk_space-0.1.1/
[  +13 ms] Found plugin file_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.2+2/
[   +9 ms] Found plugin file_selector at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector-0.8.2/
[   +3 ms] Found plugin file_selector_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_linux-0.0.2/
[   +3 ms] Found plugin file_selector_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_macos-0.0.4/
[   +7 ms] Found plugin file_selector_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_web-0.8.1/
[   +2 ms] Found plugin file_selector_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.0.2/
[   +8 ms] Found plugin firexcode at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firexcode-1.0.5/
[  +15 ms] Found plugin flutter_plugin_android_lifecycle at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.1/
[  +33 ms] Found plugin image_editor_pro at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_editor_pro-1.1.8/
[   +5 ms] Found plugin image_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.7.5/
[   +4 ms] Found plugin image_picker_for_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.0.0/
[  +20 ms] Found plugin package_info_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.0.1/
[   +3 ms] Found plugin package_info_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.1.1/
[   +4 ms] Found plugin package_info_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.1/
[  +10 ms] Found plugin path_provider at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[   +3 ms] Found plugin path_provider_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +4 ms] Found plugin path_provider_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +4 ms] Found plugin path_provider_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[   +3 ms] Found plugin permission_handler at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/
[  +16 ms] Found plugin share_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-2.1.2/
[   +3 ms] Found plugin share_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_macos-2.0.2/
[   +3 ms] Found plugin share_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_web-2.0.4/
[   +4 ms] Found plugin shared_preferences at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +3 ms] Found plugin shared_preferences_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +1 ms] Found plugin shared_preferences_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +2 ms] Found plugin shared_preferences_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +2 ms] Found plugin shared_preferences_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +14 ms] Found plugin url_launcher at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/
[   +2 ms] Found plugin url_launcher_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.0/
[   +1 ms] Found plugin url_launcher_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.0/
[   +2 ms] Found plugin url_launcher_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.0/
[   +1 ms] Found plugin url_launcher_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.0/
[   +3 ms] Found plugin video_player at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.1.1/
[   +3 ms] Found plugin video_player_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.0/
[   +2 ms] Found plugin wakelock at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.2/
[   +2 ms] Found plugin wakelock_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_macos-0.1.0+1/
[   +2 ms] Found plugin wakelock_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_web-0.2.0+1/
[ +700 ms] Found plugin dart_vlc at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[   +2 ms] Found plugin disk_space at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/disk_space-0.1.1/
[   +6 ms] Found plugin file_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.2+2/
[   +3 ms] Found plugin file_selector at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector-0.8.2/
[   +1 ms] Found plugin file_selector_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_linux-0.0.2/
[   +1 ms] Found plugin file_selector_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_macos-0.0.4/
[   +2 ms] Found plugin file_selector_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_web-0.8.1/
[   +1 ms] Found plugin file_selector_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.0.2/
[   +2 ms] Found plugin firexcode at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firexcode-1.0.5/
[   +7 ms] Found plugin flutter_plugin_android_lifecycle at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.1/
[  +11 ms] Found plugin image_editor_pro at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_editor_pro-1.1.8/
[   +2 ms] Found plugin image_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.7.5/
[   +2 ms] Found plugin image_picker_for_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.0.0/
[  +13 ms] Found plugin package_info_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.0.1/
[   +3 ms] Found plugin package_info_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.1.1/
[   +3 ms] Found plugin package_info_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.1/
[   +7 ms] Found plugin path_provider at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[   +3 ms] Found plugin path_provider_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +2 ms] Found plugin path_provider_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +5 ms] Found plugin path_provider_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[   +3 ms] Found plugin permission_handler at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/
[  +13 ms] Found plugin share_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-2.1.2/
[   +4 ms] Found plugin share_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_macos-2.0.2/
[   +4 ms] Found plugin share_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_web-2.0.4/
[   +3 ms] Found plugin shared_preferences at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +2 ms] Found plugin shared_preferences_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +2 ms] Found plugin shared_preferences_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +3 ms] Found plugin shared_preferences_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +5 ms] Found plugin shared_preferences_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +14 ms] Found plugin url_launcher at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/
[   +1 ms] Found plugin url_launcher_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.0/
[   +1 ms] Found plugin url_launcher_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.0/
[   +3 ms] Found plugin url_launcher_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.0/
[   +1 ms] Found plugin url_launcher_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.0/
[   +2 ms] Found plugin video_player at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.1.1/
[   +4 ms] Found plugin video_player_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.0/
[   +1 ms] Found plugin wakelock at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.2/
[   +1 ms] Found plugin wakelock_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_macos-0.1.0+1/
[   +4 ms] Found plugin wakelock_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_web-0.2.0+1/
[  +31 ms] Generating /root/parts/xifair-admin/build/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +141 ms] Building without sound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +27 ms] Building Linux application...
[  +37 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /root/parts/xifair-admin/build/linux
[+8829 ms] -- The CXX compiler identification is Clang 6.0.0
[ +156 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[ +377 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- works
[   +3 ms] -- Detecting CXX compiler ABI info
[ +127 ms] -- Detecting CXX compiler ABI info - done
[   +4 ms] -- Detecting CXX compile features
[ +532 ms] -- Detecting CXX compile features - done
[ +175 ms] -- Found PkgConfig: /snap/flutter/current/usr/bin/pkg-config (found version "0.29.1") 
[   +1 ms] -- Checking for module 'gtk+-3.0'
[ +564 ms] --   Found gtk+-3.0, version 3.22.30
[ +102 ms] -- Checking for module 'glib-2.0'
[  +26 ms] --   Found glib-2.0, version 2.56.4
[  +61 ms] -- Checking for module 'gio-2.0'
[  +22 ms] --   Found gio-2.0, version 2.56.4
[  +62 ms] -- Checking for module 'blkid'
[  +26 ms] --   Found blkid, version 2.31.1
[  +65 ms] -- Checking for module 'liblzma'
[  +22 ms] --   Found liblzma, version 5.2.2
[ +160 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/CMakeLists.txt:9 (cmake_minimum_required):
[  +33 ms]   CMake 3.15 or higher is required.  You are running version 3.10.2
[   +2 ms] -- Configuring incomplete, errors occurred!
[   +5 ms] See also "/root/parts/xifair-admin/build/build/linux/x64/release/CMakeFiles/CMakeOutput.log".
[  +97 ms] Building Linux application... (completed in 11.5s)
[   +2 ms] "flutter linux" took 13,503ms.
[  +17 ms] Unable to generate build files
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmake (package:flutter_tools/src/linux/build_linux.dart:155:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:75:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:88:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +261 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
Failed to run 'flutter build linux --release -v -t lib/main.dart' for 'xifair-admin': Exited with code 1.
Verify that the part is using the correct parameters and try again.
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
```
any help will be appreciated.

**Comment by alexmercerind** [comment]
@deut818 
Your log says ```CMake 3.15 or higher is required.  You are running version 3.10.2```.

So, you should upgrade your CMake.
Alternatively, you can try to edit the plugin's `CMakeLists.txt` manually to 3.10 instead of 3.15 I'd that works.
