### ISSUE TITLE
Error while running ffi example and flutter example

### ISSUE THREAD

**Issue by Akaatsukhi** [alexmercerind/dart_vlc#83]
**Note** :- I have already install vlc and libvlc-dev. 

**Error running main example :-**

**Error :-**
```
vibe@pop-os:~/Downloads/dart_vlc/example$ flutter build linux

💪 Building with sound null safety 💪

/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/callbackmanager.hpp:155:5: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/dart_vlc.cpp:86:9: error: taking the address of a temporary object of type 'Playlist' [-Waddress-of-temporary]
Building Linux application...                                           
Build process failed
```

**verbose output :-**
```
vibe@pop-os:~/Downloads/dart_vlc/example$ flutter build linux -v
[  +58 ms] executing: uname -m
[  +27 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] executing: [/home/vibe/fvm/versions/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] executing: [/home/vibe/fvm/versions/stable/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +15 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +5 ms] executing: [/home/vibe/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/vibe/fvm/versions/stable/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +70 ms] Unable to locate an Android SDK.
[   +6 ms] executing: [/home/vibe/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +56 ms] Skipping pub get: version match.
[  +27 ms] Found plugin path_provider at /home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +6 ms] Found plugin path_provider_linux at
/home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +4 ms] Found plugin path_provider_macos at
/home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +4 ms] Found plugin path_provider_windows at
/home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +9 ms] Found plugin dart_vlc at /home/vibe/Downloads/dart_vlc/
[ +290 ms] Found plugin path_provider at /home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +2 ms] Found plugin path_provider_linux at
/home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_macos at
/home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +3 ms] Found plugin path_provider_windows at
/home/vibe/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +8 ms] Found plugin dart_vlc at /home/vibe/Downloads/dart_vlc/
[  +10 ms] Generating
/home/vibe/Downloads/dart_vlc/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +66 ms] 💪 Building with sound null safety 💪
[  +10 ms] Building Linux application...
[  +17 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/vibe/Downloads/dart_vlc/example/linux
[  +41 ms] -- Configuring done
[   +6 ms] -- Generating done
[   +7 ms] -- Build files have been written to: /home/vibe/Downloads/dart_vlc/example/build/linux/x64/release
[   +7 ms] executing: ninja -C build/linux/x64/release install
[   +9 ms] ninja: Entering directory `build/linux/x64/release'
[+1786 ms] [1/10] Building CXX object plugins/dart_vlc/CMakeFiles/dartvlc.dir/__/ffi/native/dart_vlc.cpp.o
[        ] FAILED: plugins/dart_vlc/CMakeFiles/dartvlc.dir/__/ffi/native/dart_vlc.cpp.o 
[  +31 ms] /usr/bin/clang++ -DAPPLICATION_ID=\"com.example.example\" -Ddartvlc_EXPORTS
-I/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dartvlc
-I/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/INTERFACE
-I/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/external/libvlcpp-mast
er -I/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/dart_vlc_plugin
-I/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/include -O3 -DNDEBUG
-fPIC -std=gnu++17 -MD -MT plugins/dart_vlc/CMakeFiles/dartvlc.dir/__/ffi/native/dart_vlc.cpp.o -MF
plugins/dart_vlc/CMakeFiles/dartvlc.dir/__/ffi/native/dart_vlc.cpp.o.d -o
plugins/dart_vlc/CMakeFiles/dartvlc.dir/__/ffi/native/dart_vlc.cpp.o -c
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/dart_vlc.cpp
[   +2 ms] In file included from
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/dart_vlc.cpp:19:
[        ] In file included from
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/eventmanager.hpp:12
:
[        ]
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/callbackmanager.hpp
:155:5: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'?
[-Wmismatched-new-delete]
[   +4 ms]     delete values;
[        ]     ^
[        ]           []
[        ]
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/callbackmanager.hpp
:147:29: note: allocated with 'new[]' here
[        ]     Dart_CObject** values = new Dart_CObject*[2];
[        ]                             ^
[        ]
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/ffi/native/dart_vlc.cpp:86:9:
error: taking the address of a temporary object of type 'Playlist' [-Waddress-of-temporary]
[        ]         &Playlist(medias),
[        ]         ^~~~~~~~~~~~~~~~~
[        ] 1 warning and 1 error generated.
[+26749 ms] [2/10] Generating /home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/vibe/Downloads/dart_vlc/example/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +2 ms] [  +65 ms] executing: uname -m
[        ] [  +31 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +6 ms] executing: [/home/vibe/fvm/versions/stable/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] [        ] executing: [/home/vibe/fvm/versions/stable/] git tag --points-at
f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] [  +15 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] [        ] 2.2.3
[        ] [   +5 ms] executing: [/home/vibe/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/vibe/fvm/versions/stable/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +49 ms] Unable to locate an Android SDK.
[        ] [   +7 ms] executing: [/home/vibe/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +78 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +28 ms] Initializing file store
[        ] [  +21 ms] Skipping target: gen_localizations
[        ] [   +6 ms] unpack_linux: Starting due to {}
[        ] [  +50 ms] kernel_snapshot: Starting due to {}
[        ] [   +3 ms] unpack_linux: Complete
[   +1 ms] [ +771 ms] /home/vibe/fvm/versions/stable/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/vibe/fvm/versions/stable/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/vibe/fvm/versions/stable/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter
--no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages
/home/vibe/Downloads/dart_vlc/example/.dart_tool/package_config.json --output-dill
/home/vibe/Downloads/dart_vlc/example/.dart_tool/flutter_build/f679ab19a8d97f0a5c5ba03bc352c692/app.dill --depfile
/home/vibe/Downloads/dart_vlc/example/.dart_tool/flutter_build/f679ab19a8d97f0a5c5ba03bc352c692/kernel_snapshot.d
package:dart_vlc_example/main.dart
[        ] [+17500 ms] kernel_snapshot: Complete
[        ] [ +323 ms] aot_elf_release: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents:
/home/vibe/fvm/versions/stable/packages/flutter_tools/lib/src/build_system/targets/common.dart,/home/vibe/Downloads/da
rt_vlc/example/.dart_tool/flutter_build/f679ab19a8d97f0a5c5ba03bc352c692/app.dill,/home/vibe/fvm/versions/stable/bin/i
nternal/engine.version,/home/vibe/fvm/versions/stable/bin/internal/engine.version,/home/vibe/fvm/versions/stable/bin/i
nternal/engine.version}
[   +1 ms] [   +4 ms] executing:
/home/vibe/fvm/versions/stable/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic
--snapshot_kind=app-aot-elf
--elf=/home/vibe/Downloads/dart_vlc/example/.dart_tool/flutter_build/f679ab19a8d97f0a5c5ba03bc352c692/app.so --strip
/home/vibe/Downloads/dart_vlc/example/.dart_tool/flutter_build/f679ab19a8d97f0a5c5ba03bc352c692/app.dill
[        ] [+8514 ms] aot_elf_release: Complete
[        ] [  +37 ms] linux_aot_bundle: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents:
/home/vibe/Downloads/dart_vlc/example/.dart_tool/flutter_build/f679ab19a8d97f0a5c5ba03bc352c692/app.so}
[        ] [   +4 ms] linux_aot_bundle: Complete
[        ] [  +36 ms] release_bundle_linux-x64_assets: Starting due to {}
[        ] [  +97 ms] release_bundle_linux-x64_assets: Complete
[        ] [  +37 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[        ] [   +7 ms] "flutter assemble" took 27,557ms.
[        ] [ +256 ms] ensureAnalyticsSent: 252ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +1 ms] exiting with code 0
[        ] ninja: build stopped: subcommand failed.
[  +15 ms] Building Linux application... (completed in 28.7s)
[   +1 ms] "flutter linux" took 29,273ms.
[   +5 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:186:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:78:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:88:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

**Error while running ffi example :-**

```
vibe@pop-os:~/Downloads/dart_vlc/ffi$ dart example.dart 
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/home/vibe/Downloads/dart_vlc/ffi/dart_vlc.so': /home/vibe/Downloads/dart_vlc/ffi/dart_vlc.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      DartVLC.initialize (package:dart_vlc_ffi/src/internal/initializer.dart:9:39)
#3      main (file:///home/vibe/Downloads/dart_vlc/ffi/example.dart:8:11)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


```

**Comment by alexmercerind** [comment]
Thanks a lot for this report.

**Comment by alexmercerind** [comment]
Thankyou for this report. It was really a very critical issue.

It's fixed on the master now. Please use the plugin from git for now.

Let me know if something else is also broken.
